#!/bin/bash


unzip -qc START.pptx  ppt/slides/slide*.xml | grep -oP '(?<=\<a:t\>).*?(?=\</a:t\>)' > temp.txt

NEXTS=`cat temp.txt | head -n 1 | cut -d"," -f2`
NEXTSN=`cat temp.txt | head -n 1 | cut -d"," -f3`
printf `cat temp.txt | head -n 1 | cut -d"," -f1`
#echo "next file: $NEXTS"
#echo "next slide number: $NEXTSN"
echo `cat temp.txt | head -n 1` > temp.txt
#echo `cat temp.txt`

COUNT=1
while [ $COUNT -gt 0 ]; do
	FOUND=`ls | grep -c $NEXTS`
	#echo "found: $FOUND"
	if [[ $FOUND == 0 ]]
	then
		break
	fi
	echo `unzip -qc $NEXTS  ppt/slides/slide*.xml | grep -oP '(?<=\<a:t\>).*?(?=\</a:t\>)'` > temp.txt

	COUNT=`cat temp.txt | wc -w`
	#echo "count is: $COUNT nextsn is $NEXTSN"
	if [[ $((COUNT < 3*NEXTSN)) != 0 ]] 
	then
		echo "breaking"
		break
	fi
	F=$NEXTSN
	F=$((F - 1))
	F=$((F * 3 + 1))
	E=$((F + 2))
	#echo "F is: $F"
	echo `cat temp.txt | cut -d" " -f$F-$E` > temp.txt
	printf `cat temp.txt | cut -d"," -f1`
	NEXTS=`cat temp.txt | cut -d"," -f2`
	NEXTSN=`cat temp.txt | cut -d"," -f3`
	#echo "next file: $NEXTS"
	#echo "next slide number: $NEXTSN"


done
printf "\n"
	


